# Generated by Django 5.0.4 on 2024-06-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='text',
            new_name='discription',
        ),
    ]
