# Generated by Django 5.0.4 on 2024-06-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_rename_text_product_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
