# Generated by Django 5.0.4 on 2024-06-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheapest',
            old_name='price',
            new_name='product',
        ),
        migrations.AddField(
            model_name='cheapest',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
