# Generated by Django 4.1 on 2024-06-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_rename_price_cheapest_product_cheapest_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheapest',
            name='quantity',
        ),
    ]
